services:
  bot:
    container_name: welcome_bot
    build: .
    env_file:
      - ./.env
    # volumes:
    #   - ./src:/api
    networks:
      - api_net
    restart: always

networks:
  api_net:
    name: api_net
